/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.menu;

import com.RegistrarVentaCotizacion.FrameVentaCotizacion;
import com.categoria.FrameCategoria;
import com.clientes.interfazClientes;
import com.cotizacion.FrameGenerarCotizacion;
import com.registrarGastos.FrameRegistrarGastos;
import java.awt.Color;

/**
 *
 * @author ADM
 */
public class menu2 extends javax.swing.JFrame {

    int xMouse, yMouse;
    public menu2() {
        initComponents();
        header.setBackground(new Color(0,0,0,0));
        xPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        xTxt = new javax.swing.JLabel();
        xPanel = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        ClientesTxt = new javax.swing.JLabel();
        ClientesPanel = new javax.swing.JPanel();
        CategoriaTxt = new javax.swing.JLabel();
        CategoriaPanel = new javax.swing.JPanel();
        RegistrarGastosTxt = new javax.swing.JLabel();
        RegistrarGastosPanel = new javax.swing.JPanel();
        CotizacionTxt = new javax.swing.JLabel();
        CotizacionPanel = new javax.swing.JPanel();
        VentaCotizacionTxt = new javax.swing.JLabel();
        VentaCotizacionPanel = new javax.swing.JPanel();
        ReporteDeVentasTxt = new javax.swing.JLabel();
        ReporteDeVentasPanel = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        xTxt.setForeground(new java.awt.Color(0, 0, 0));
        xTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xTxt.setText("X");
        xTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xTxtMouseExited(evt);
            }
        });
        panelFondo.add(xTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        xPanel.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout xPanelLayout = new javax.swing.GroupLayout(xPanel);
        xPanel.setLayout(xPanelLayout);
        xPanelLayout.setHorizontalGroup(
            xPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        xPanelLayout.setVerticalGroup(
            xPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelFondo.add(xPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelFondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        ClientesTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ClientesTxt.setForeground(new java.awt.Color(0, 0, 0));
        ClientesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientesTxt.setText("Clientes");
        ClientesTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClientesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientesTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientesTxtMouseExited(evt);
            }
        });
        panelFondo.add(ClientesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 50));

        ClientesPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout ClientesPanelLayout = new javax.swing.GroupLayout(ClientesPanel);
        ClientesPanel.setLayout(ClientesPanelLayout);
        ClientesPanelLayout.setHorizontalGroup(
            ClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        ClientesPanelLayout.setVerticalGroup(
            ClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelFondo.add(ClientesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 50));

        CategoriaTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CategoriaTxt.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoriaTxt.setText("Categoria");
        CategoriaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategoriaTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CategoriaTxtMouseExited(evt);
            }
        });
        panelFondo.add(CategoriaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 50));

        CategoriaPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout CategoriaPanelLayout = new javax.swing.GroupLayout(CategoriaPanel);
        CategoriaPanel.setLayout(CategoriaPanelLayout);
        CategoriaPanelLayout.setHorizontalGroup(
            CategoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        CategoriaPanelLayout.setVerticalGroup(
            CategoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelFondo.add(CategoriaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        RegistrarGastosTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        RegistrarGastosTxt.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarGastosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarGastosTxt.setText("Registrar Gastos");
        RegistrarGastosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarGastosTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarGastosTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarGastosTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarGastosTxtMouseExited(evt);
            }
        });
        panelFondo.add(RegistrarGastosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 50));

        RegistrarGastosPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout RegistrarGastosPanelLayout = new javax.swing.GroupLayout(RegistrarGastosPanel);
        RegistrarGastosPanel.setLayout(RegistrarGastosPanelLayout);
        RegistrarGastosPanelLayout.setHorizontalGroup(
            RegistrarGastosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        RegistrarGastosPanelLayout.setVerticalGroup(
            RegistrarGastosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelFondo.add(RegistrarGastosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        CotizacionTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CotizacionTxt.setForeground(new java.awt.Color(0, 0, 0));
        CotizacionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CotizacionTxt.setText("Cotización");
        CotizacionTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CotizacionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CotizacionTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CotizacionTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CotizacionTxtMouseExited(evt);
            }
        });
        panelFondo.add(CotizacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 50));

        CotizacionPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout CotizacionPanelLayout = new javax.swing.GroupLayout(CotizacionPanel);
        CotizacionPanel.setLayout(CotizacionPanelLayout);
        CotizacionPanelLayout.setHorizontalGroup(
            CotizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        CotizacionPanelLayout.setVerticalGroup(
            CotizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelFondo.add(CotizacionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 50));

        VentaCotizacionTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        VentaCotizacionTxt.setForeground(new java.awt.Color(0, 0, 0));
        VentaCotizacionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VentaCotizacionTxt.setText("Venta Cotización");
        VentaCotizacionTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentaCotizacionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentaCotizacionTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentaCotizacionTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VentaCotizacionTxtMouseExited(evt);
            }
        });
        panelFondo.add(VentaCotizacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, 50));

        VentaCotizacionPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout VentaCotizacionPanelLayout = new javax.swing.GroupLayout(VentaCotizacionPanel);
        VentaCotizacionPanel.setLayout(VentaCotizacionPanelLayout);
        VentaCotizacionPanelLayout.setHorizontalGroup(
            VentaCotizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        VentaCotizacionPanelLayout.setVerticalGroup(
            VentaCotizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelFondo.add(VentaCotizacionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        ReporteDeVentasTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ReporteDeVentasTxt.setForeground(new java.awt.Color(0, 0, 0));
        ReporteDeVentasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReporteDeVentasTxt.setText("Reporte de Ventas");
        ReporteDeVentasTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReporteDeVentasTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReporteDeVentasTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReporteDeVentasTxtMouseExited(evt);
            }
        });
        panelFondo.add(ReporteDeVentasTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 160, 50));

        ReporteDeVentasPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout ReporteDeVentasPanelLayout = new javax.swing.GroupLayout(ReporteDeVentasPanel);
        ReporteDeVentasPanel.setLayout(ReporteDeVentasPanelLayout);
        ReporteDeVentasPanelLayout.setHorizontalGroup(
            ReporteDeVentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        ReporteDeVentasPanelLayout.setVerticalGroup(
            ReporteDeVentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelFondo.add(ReporteDeVentasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/bg.png"))); // NOI18N
        panelFondo.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void xTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseEntered
        xTxt.setForeground(Color.white);
        xPanel.setVisible(true);
    }//GEN-LAST:event_xTxtMouseEntered

    private void xTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseExited
        xTxt.setForeground(Color.black);
        xPanel.setVisible(false);
    }//GEN-LAST:event_xTxtMouseExited

    private void xTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xTxtMouseClicked

    private void ClientesTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesTxtMouseEntered
//        ClientesPanel.setBackground(new Color(51,51,51));
//        ClientesTxt.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_ClientesTxtMouseEntered

    private void ClientesTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesTxtMouseExited
//        ClientesPanel.setBackground(new Color(204,204,204));
//        ClientesTxt.setForeground(Color.black);
    }//GEN-LAST:event_ClientesTxtMouseExited

    private void CotizacionTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotizacionTxtMouseEntered
//        CotizacionPanel.setBackground(new Color(51,51,51));
//        CotizacionTxt.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_CotizacionTxtMouseEntered

    private void CotizacionTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotizacionTxtMouseExited
//        CotizacionPanel.setBackground(new Color(204,204,204));
//        CotizacionTxt.setForeground(Color.black);
    }//GEN-LAST:event_CotizacionTxtMouseExited
    private void CategoriaTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaTxtMouseEntered
//        CategoriaPanel.setBackground(new Color(51,51,51));
//        CategoriaTxt.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_CategoriaTxtMouseEntered

    private void CategoriaTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaTxtMouseExited
//        CategoriaPanel.setBackground(new Color(204,204,204));
//        CategoriaTxt.setForeground(Color.black);
    }//GEN-LAST:event_CategoriaTxtMouseExited

    private void VentaCotizacionTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaCotizacionTxtMouseEntered
//        VentaCotizacionPanel.setBackground(new Color(51,51,51));
//        VentaCotizacionTxt.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_VentaCotizacionTxtMouseEntered

    private void VentaCotizacionTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaCotizacionTxtMouseExited
//        VentaCotizacionPanel.setBackground(new Color(204,204,204));
//        VentaCotizacionTxt.setForeground(Color.black);
    }//GEN-LAST:event_VentaCotizacionTxtMouseExited

    private void RegistrarGastosTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarGastosTxtMouseEntered
//        RegistrarGastosPanel.setBackground(new Color(51,51,51));
//        RegistrarGastosTxt.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_RegistrarGastosTxtMouseEntered

    private void RegistrarGastosTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarGastosTxtMouseExited
//        RegistrarGastosPanel.setBackground(new Color(204,204,204));
//        RegistrarGastosTxt.setForeground(Color.black);
    }//GEN-LAST:event_RegistrarGastosTxtMouseExited

    private void ReporteDeVentasTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteDeVentasTxtMouseEntered
//        ReporteDeVentasPanel.setBackground(new Color(51,51,51));
//        ReporteDeVentasTxt.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_ReporteDeVentasTxtMouseEntered

    private void ReporteDeVentasTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteDeVentasTxtMouseExited
//        ReporteDeVentasPanel.setBackground(new Color(204,204,204));
//        ReporteDeVentasTxt.setForeground(Color.black);
    }//GEN-LAST:event_ReporteDeVentasTxtMouseExited

    private void ClientesTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesTxtMouseClicked
        this.setVisible(false);
        interfazClientes clientes=new interfazClientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_ClientesTxtMouseClicked

    private void CategoriaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaTxtMouseClicked
        this.setVisible(false);
        FrameCategoria categoria=new FrameCategoria();
        categoria.setVisible(true);
    }//GEN-LAST:event_CategoriaTxtMouseClicked

    private void VentaCotizacionTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaCotizacionTxtMouseClicked
        this.setVisible(false);
        FrameVentaCotizacion ventaCotizacion=new FrameVentaCotizacion();
        ventaCotizacion.setVisible(true);
    }//GEN-LAST:event_VentaCotizacionTxtMouseClicked

    private void RegistrarGastosTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarGastosTxtMouseClicked
        this.setVisible(false);
        FrameRegistrarGastos registrarGastos=new FrameRegistrarGastos();
        registrarGastos.setVisible(true);
    }//GEN-LAST:event_RegistrarGastosTxtMouseClicked

    private void CotizacionTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotizacionTxtMouseClicked
        this.setVisible(false);
        FrameGenerarCotizacion frame=new FrameGenerarCotizacion();
        frame.setVisible(true);
    }//GEN-LAST:event_CotizacionTxtMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoriaPanel;
    private javax.swing.JLabel CategoriaTxt;
    private javax.swing.JPanel ClientesPanel;
    private javax.swing.JLabel ClientesTxt;
    private javax.swing.JPanel CotizacionPanel;
    private javax.swing.JLabel CotizacionTxt;
    private javax.swing.JPanel RegistrarGastosPanel;
    private javax.swing.JLabel RegistrarGastosTxt;
    private javax.swing.JPanel ReporteDeVentasPanel;
    private javax.swing.JLabel ReporteDeVentasTxt;
    private javax.swing.JPanel VentaCotizacionPanel;
    private javax.swing.JLabel VentaCotizacionTxt;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel header;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel xPanel;
    private javax.swing.JLabel xTxt;
    // End of variables declaration//GEN-END:variables
}
